package academy.starci.val;

import java.util.Map;

/**
 * Plain Java class representing a user record returned in API responses.
 *
 * This class is serialised to JSON by Spring's Jackson integration.
 * Field order in the JSON output follows Jackson's default (alphabetical when no annotation).
 * The {@code address} field is typed as {@code Map<String, Object>} so it can hold
 * arbitrary nested JSON without requiring a dedicated AddressDto class in Java.
 */
public class User {

    /** Unique short identifier generated by the in-memory store (e.g. "wl03f8"). */
    private String id;

    /** Display name of the user, validated to be at least 3 characters. */
    private String name;

    /** Email address of the user, validated to contain "@". */
    private String email;

    /** Age in years, validated to be an integer in [18, 100]. */
    private Integer age;

    /**
     * Optional postal address as a free-form map.
     * Null when the client did not supply an address in the request body.
     * The map must contain "city" (string) and "zip" (4-10 digit string) if present.
     */
    private Map<String, Object> address;

    /** Default no-arg constructor required by Jackson for deserialisation. */
    public User() {}

    /**
     * All-args constructor used by the controller when creating a new user.
     *
     * @param id      Generated unique identifier.
     * @param name    Validated display name.
     * @param email   Validated email address.
     * @param age     Validated age integer.
     * @param address Optional address map; null if not supplied.
     */
    public User(String id, String name, String email, Integer age, Map<String, Object> address) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.age = age;
        this.address = address;
    }

    // --- Getters and setters (Jackson uses these for JSON serialisation/deserialisation) ---

    /** @return the user's unique identifier. */
    public String getId() {
        return id;
    }

    /** @param id the identifier to assign. */
    public void setId(String id) {
        this.id = id;
    }

    /** @return the user's display name. */
    public String getName() {
        return name;
    }

    /** @param name the display name to assign. */
    public void setName(String name) {
        this.name = name;
    }

    /** @return the user's email address. */
    public String getEmail() {
        return email;
    }

    /** @param email the email address to assign. */
    public void setEmail(String email) {
        this.email = email;
    }

    /** @return the user's age in years. */
    public Integer getAge() {
        return age;
    }

    /** @param age the age value to assign. */
    public void setAge(Integer age) {
        this.age = age;
    }

    /** @return the optional address map, or null if absent. */
    public Map<String, Object> getAddress() {
        return address;
    }

    /** @param address the address map to assign; pass null to indicate no address. */
    public void setAddress(Map<String, Object> address) {
        this.address = address;
    }
}
